//  API Engines Image Processor Delegate
//
//  kfxKIPDelegate.h
//  kfxLibEngines
//
//  Created by Mark Day on 9/18/13.
//  Copyright (c) 2012 - 2014 Kofax. Use of this code is with permission pursuant to Kofax license terms.
//
#import <Foundation/Foundation.h>
#import "kfxKEDImage.h"

//!  Image Processing Protocol
/**
 The kfxKIPDelegate defines the protocol for all the delegates the Image Processsing Engine calls during image processing.  There is a pair for quick analysis, and a pair for process image.  Each pair consists of a progress event to inform you of the completion precentage and an operation complete event after the final image processing ends.  The library uses these delegates during processing because they are completed in background.    
 */

@protocol kfxKIPDelegate <NSObject>
@required

//!  Image Out Delegate
/**
 The Engine calls this method after an image is generated by image processing.\n
 This is a required delegate. The output image contains the processed image if no error was detected.\n
 @param  status : Set to KMC_SUCCESS if no error occurred, otherwise an error code.
 @param  errorMsg : A description of the error that occurred.
 @param  kfxImage : An output image reference when image processing completed without error.
 */
- (void)imageOut:(int)status withMsg: (NSString*) errorMsg andOutputImage: (kfxKEDImage*) kfxImage;


//!  Image processing progress Delegate
/**
 The Engine calls this method multiple times during processing to indicate progress in percent, from 1-100.\n
 This is a required delegate. You should make no decisions about the image processing until the library calls the image out delegate.\n
 @param  status  Set to KMC_SUCCESS if no error occurred, otherwise an error code.
 @param  errorMsg  A description of the error that occurred.
 @param  imageID   The ID of the original input image
 @param  percent   The percentage of completion, 1-100
 */
- (void)processProgress: (int) status withMsg: (NSString*) errorMsg imageID: (NSString*) imageID andProgress: (int) percent;


//!  Analysis Complete Delegate
/**
 The Engine calls this method after the engine completes the quick analysis.\n
 This is a required delegate. The output kfxImage is the original input image given for analysis.  The results of the quick analysis are stored in this input kfxImage regardless if you requested an output image or not.  If you did request a quick analysis image, then the UIImage image is stored in the quickAnalysisFeedback element of the input kfxImage.\n
 @param  status : Set to KMC_SUCCESS if no error occurred, otherwise an error code.
 @param  errorMsg : A description of the error that occurred.
 @param  kfxImage : A reference to the input image, regardless of if an error was generated.
 */
- (void)analysisComplete:(int)status withMsg: (NSString*) errorMsg andOutputImage: (kfxKEDImage*) kfxImage;


//!  Image analysis progress Delegate
/**
 The Engine calls this method multiple times during processing to indicate progress in percent, from 1-100.\n
 This is a required delegate. You should make no decisions about the image processing until the library calls the analysis complete delegate.\n
 @param  status  Set to KMC_SUCCESS if no error occurred, otherwise an error code.
 @param  errorMsg  A description of the error that occurred.
 @param  imageID   The ID of the original input image
 @param  percent   The percentage of completion, 1-100
 */

- (void)analysisProgress: (int) status withMsg: (NSString*) errorMsg imageID: (NSString*) imageID andProgress: (int) percent;

@end
